/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Highlight: typeof import('./src/components/Highlight.vue')['default']
    PluginCard: typeof import('./src/components/PluginCard.vue')['default']
    PluginFilter: typeof import('./src/components/PluginFilter.vue')['default']
    Plugins: typeof import('./src/components/Plugins.vue')['default']
  }
}
