import { definePlugin, PluginCategory, PluginStatus, html } from '~/util'
import { nanoid } from "nanoid";

const r = nanoid();

export default definePlugin({
  name: 'auto-install',
  description: 'Automatically install dependencies that are imported by a bundle',
  link: 'https://github.com/vitejs/vite/issues/1500',
  status: PluginStatus.Incompatible,
  category: PluginCategory.Official,
  enforce: 'pre',
  demo() {
    return html`
      <p>Fails at build time, there is an active PR to fix the issue</p>
      <p>
        Test it by uninstalling nanoid from the project. The auto-install plugin
        will add it back
      </p>
      <pre>string generated by nanoid: ${r}</pre>
    `
  },
})
