<template>
  <PluginCard
    :official="true"
    name="auto-install"
    description="Automatically install dependencies that are imported by a bundle"
    enforce="pre"
    status="incompatible"
    link="https://github.com/vitejs/vite/issues/1500"
  >
    <p>Fails at build time, there is an active PR to fix the issue</p>
    <p>
      Test it by uninstalling nanoid from the project. The auto-install plugin
      will add it back
    </p>
    <pre>string generated by nanoid: {{ r }}</pre>
  </PluginCard>
</template>

<script setup>
import PluginCard from "../PluginCard.vue";
import { nanoid } from "nanoid";

const r = nanoid();
</script>

