<template>
  <p>Fails at build time, there is an active PR to fix the issue</p>
  <p>
    Test it by uninstalling nanoid from the project. The auto-install plugin
    will add it back
  </p>
  <pre>string generated by nanoid: {{ r }}</pre>
</template>

<script setup>
import { nanoid } from "nanoid";

const r = nanoid();
</script>

