<template>
  <PluginTest
    name="auto-install"
    description="Automatically install dependencies that are imported by a bundle"
    enforce="pre"
    status="incompatible"
  >
    <p>Fails at build time</p>
    <p>
      Test it by uninstalling nanoid from the project. The auto-install plugin
      will add it back
    </p>
    <pre>string generated by nanoid: {{ r }}</pre>
  </PluginTest>
</template>

<script setup>
import PluginTest from "../PluginTest.vue";
import { nanoid } from "nanoid";

const r = nanoid();
</script>

